service: aws-finaltest
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  health: ${file(src/functions/health/index.yml):health}

plugins:
  - serverless-offline
  - serverless-plugin-typescript
