service: aws-finaltest
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
