service: aws-finaltest
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    AWS_REGION: ${env:AWS_REGION}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    S3_BUCKET: ${env:S3_BUCKET}

functions:
  health: ${file(src/functions/health/index.yml):health}

  # USER
  createUser: ${file(src/functions/user/create/index.yml):createUser}
  # findUser: ${file(src/functions/user/find/index.yml):findUser}
  # updateUser: ${file(src/functions/user/update/index.yml):updateUser}
  # deleteUser: ${file(src/functions/user/delete/index.yml):deleteUser}

  # CONFIG
  createConfig: ${file(src/functions/Config/create/index.yml):createConfig}
  findConfig: ${file(src/functions/Config/find/index.yml):findConfig}

plugins:
  - serverless-offline
  - serverless-plugin-typescript
