service: aws-finaltest
configValidationMode: error
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512
  environment:
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    REGION: ${env:REGION}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    S3_BUCKET: ${env:S3_BUCKET}
    TURSO_DATABASE_URL: ${env:TURSO_DATABASE_URL}
    TURSO_AUTH_TOKEN: ${env:TURSO_AUTH_TOKEN}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::${env:S3_BUCKET}"
            - "arn:aws:s3:::${env:S3_BUCKET}/*"
        - Effect: "Allow"
          Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
          Resource:
            - "*"
custom:
  prune:
    automatic: true
    number: 0

functions:
  health: ${file(src/functions/health/index.yml):health}

  # USER
  createUser: ${file(src/functions/user/create/index.yml):createUser}
  findUser: ${file(src/functions/user/find/index.yml):findUser}
  loginUser: ${file(src/functions/user/logIn/index.yml):userLogin}
  # updateUser: ${file(src/functions/user/update/index.yml):updateUser}

  # CONFIG
  createConfig: ${file(src/functions/Config/create/index.yml):createConfig}
  findConfig: ${file(src/functions/Config/find/index.yml):findConfig}
  listConfig: ${file(src/functions/Config/list/index.yml):listConfig}

  # CONSULTANCY
  createConsultancy: ${file(src/functions/consultancies/create/index.yml):createConsultancy}

  # DOCUMENT
  createDocument: ${file(src/functions/docs/Upload/index.yml):createDocument}

  #Currency
  listCurrency: ${file(src/functions/Currency/list/index.yml):listCurrency}

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-prune-plugin
